### PR TITLE
Change the color notation to Hex

### PR DESCRIPTION
**Pull request by ghost**
Changing the color notation to Hex allows tcpdf to display the generated barcode correctly - without this change the barcode will be rendered in white.

I believe the SVG spec only supports CSS2 as per http://www.w3.org/TR/2003/REC-SVG11-20030114/REC-SVG11-20030114.pdf page 296

### CODE REVIEW

**Comment by nicolaasuni** [comment]
Merged. Please note that I am working on refactoring TCPDF to use this library and the other ones I am developing (tc-lib-...).

**Comment by fooman** [comment]
Awesome - looking forward to it.

**Comment by nicolaasuni** [comment]
I have just noticed that the constraint for CSS2 is only for SVG and not for HTML.
Additionally, next time, before submitting a PR, please execute the "make qa_all" command to see if it passes all the tests. In this case I have manually changed the tests.

**Comment by fooman** [comment]
Makes sense - will do.

**Pull request merged**
